name: BIND9

on:
 push:
 workflow_dispatch:
   inputs:
      version:
        description: 'Tag Name'
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226
      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09
        with:
          context: bind9
          push: true
          tags: ghcr.io/luotianyi-dev/bind9:${{ github.event.inputs.version || format('git-{0}', github.sha) }}
          build-args: |
            IMAGE_VERSION=${{ github.event.inputs.version || format('git-{0}', github.sha) }}
